
version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - env/.env.dev
  web:
    env_file:
      - env/.env.dev
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
